import { AgentRole } from '@/ai/agents/core/agent.types';

export type TaskCategory = 'CODING' | 'PLANNING' | 'ARCHITECTURE' | 'TESTING' | 'DOCUMENTATION' | 'ANALYSIS' | 'CONVERSATION';

const ROLE_TASK_CATEGORY: Record<AgentRole, TaskCategory> = {
  CEO: 'PLANNING',
  ARCHITECT: 'ARCHITECTURE',
  DEVELOPER: 'CODING',
  FRONTEND: 'CODING',
  BACKEND: 'CODING',
  DATABASE: 'ARCHITECTURE',
  QA: 'TESTING',
  PRODUCT_MANAGER: 'PLANNING',
  REVIEWER: 'ANALYSIS',
  ARCHITECTURE_REVIEWER: 'ARCHITECTURE',
  CODE_REVIEWER: 'CODING',
  QUALITY_REVIEWER: 'TESTING',
  DOCUMENTATION: 'DOCUMENTATION',
  DEVOPS: 'CODING',
  UI_UX: 'CODING',
  SECURITY: 'ANALYSIS',
  PRODUCT_DISCOVERY: 'PLANNING',
  OPERATIONS: 'ANALYSIS',
  BUSINESS_ANALYST: 'ANALYSIS',
  UX_RESEARCHER: 'ANALYSIS',
  UI_DESIGNER: 'CODING',
};

export function classifyTask(role: AgentRole): TaskCategory {
  return ROLE_TASK_CATEGORY[role];
}
