'use client';

import React, { useState } from 'react';
import { toast } from 'sonner';
import {
  Network,
  Copy,
  Check,
  Database,
  GitBranch,
  Layers,
  Sparkles,
  Workflow,
  Cpu,
  Shield,
  Code2,
} from 'lucide-react';
import { GlassCard, NeonButton } from '@/packages/ui';
import {
  ArchitectureDiagramCatalog,
  type ArchitectureDiagramType,
  MermaidDiagramRenderer,
} from '@/packages/diagrams';

interface ArchitectureVisualizerPanelProps {
  projectName?: string;
}

const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  System: <Cpu className="w-3.5 h-3.5" />,
  Database: <Database className="w-3.5 h-3.5" />,
  Workflow: <Workflow className="w-3.5 h-3.5" />,
  Operations: <GitBranch className="w-3.5 h-3.5" />,
};

export function ArchitectureVisualizerPanel({ projectName = 'My Project' }: ArchitectureVisualizerPanelProps) {
  const allDiagrams = ArchitectureDiagramCatalog.getAllDiagrams();
  const [selectedType, setSelectedType] = useState<ArchitectureDiagramType>('COMPONENT');
  const [copied, setCopied] = useState(false);

  const activeDiagram = ArchitectureDiagramCatalog.getDiagram(selectedType);

  const handleCopySyntax = () => {
    navigator.clipboard.writeText(activeDiagram.mermaidSyntax);
    setCopied(true);
    toast.success('Mermaid Syntax Copied', {
      description: 'Ready to paste into GitHub Markdown or Notion docs.',
    });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <GlassCard className="w-full h-full flex flex-col p-6 border-white/10 shadow-2xl bg-surface-glass/90 overflow-hidden">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-5 mb-5 shrink-0">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <Network className="w-5 h-5 text-primary" />
            <h2 className="text-xl font-bold tracking-tight text-white">
              System Architecture Blueprint
            </h2>
          </div>
          <p className="text-xs text-white/50">
            Interactive Mermaid.js architecture diagrams generated by System Architect Marcus.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopySyntax}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl border border-white/10 bg-white/5 hover:bg-white/10 text-xs font-mono font-bold text-white transition-all shadow-sm"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-success" />
            ) : (
              <Copy className="w-3.5 h-3.5 text-primary" />
            )}
            <span>Copy Mermaid Code</span>
          </button>
        </div>
      </div>

      {/* Main Area: Split between Diagram Presets (Left) & Live Canvas (Right) */}
      <div className="flex-1 flex flex-col md:flex-row gap-6 overflow-hidden">
        {/* Left Column: Preset Catalog Selector */}
        <div className="w-full md:w-72 flex flex-col gap-2 overflow-y-auto pr-1 shrink-0 scrollbar-hide">
          <p className="text-[11px] font-mono font-bold text-white/40 uppercase tracking-wider mb-1">
            Diagram Presets ({allDiagrams.length})
          </p>
          {allDiagrams.map((d) => {
            const isSelected = selectedType === d.type;
            return (
              <button
                key={d.type}
                type="button"
                onClick={() => setSelectedType(d.type)}
                className={`p-3.5 rounded-xl border text-left transition-all flex flex-col gap-1 ${
                  isSelected
                    ? 'border-primary/80 bg-primary/20 text-white shadow-[0_0_15px_rgba(99,102,241,0.25)] ring-1 ring-primary/60'
                    : 'border-white/5 bg-white/[0.02] text-white/60 hover:text-white hover:bg-white/5'
                }`}
              >
                <div className="flex items-center justify-between gap-1">
                  <span className="text-xs font-bold tracking-tight text-white">
                    {d.title}
                  </span>
                  <span className="flex items-center gap-1 text-[9px] font-mono text-primary uppercase font-semibold">
                    {CATEGORY_ICONS[d.category]}
                    {d.category}
                  </span>
                </div>
                <p className="text-[11px] text-white/50 line-clamp-2 leading-relaxed">
                  {d.description}
                </p>
              </button>
            );
          })}
        </div>

        {/* Right Column: Live Mermaid SVG Canvas */}
        <div className="flex-1 flex flex-col rounded-2xl border border-white/10 bg-[#05050A]/95 overflow-hidden relative shadow-inner">
          {/* Canvas Top Bar */}
          <div className="flex items-center justify-between px-4 py-2.5 border-b border-white/10 bg-white/[0.02]">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
              <span className="text-xs font-mono font-bold text-white tracking-wide">
                {activeDiagram.title}
              </span>
            </div>
            <span className="text-[10px] font-mono text-white/40">
              Live Mermaid 10.x Engine
            </span>
          </div>

          {/* Canvas Body */}
          <div className="flex-1 overflow-auto p-6 flex items-center justify-center">
            <MermaidDiagramRenderer chart={activeDiagram.mermaidSyntax} />
          </div>
        </div>
      </div>
    </GlassCard>
  );
}
