'use client';

import React from 'react';
import Editor, { useMonaco } from '@monaco-editor/react';
import { GlassCard } from '@/packages/ui';
import { Loader2, Terminal, Sparkles, Cpu } from 'lucide-react';

interface CodeViewerProps {
  // The raw source code to display in the editor
  code: string;
  // The programming language (e.g., 'typescript', 'python')
  language?: string;
  // Whether the code is currently being streamed/generated by the AI
  isStreaming?: boolean;
  // Status message from the stream bus (e.g. "Alex is writing route.ts...")
  streamStatus?: string | null;
  // Number of tokens streamed so far
  tokenCount?: number;
}

/**
 * Ultra-Modern Cyber Void Live Code Viewer & Token Streamer.
 * Integrates Monaco Editor with real-time SSE token injection, smooth auto-scrolling,
 * and Cyber Void neon syntax highlighting.
 */
export function CodeViewer({
  code,
  language = 'typescript',
  isStreaming = false,
  streamStatus,
  tokenCount = 0,
}: CodeViewerProps) {
  const monaco = useMonaco();

  // Define our custom "Cyber Void" theme for Monaco when it loads
  React.useEffect(() => {
    if (monaco) {
      monaco.editor.defineTheme('cyber-void', {
        base: 'vs-dark',
        inherit: true,
        rules: [
          { token: 'comment', foreground: '64748b', fontStyle: 'italic' },
          { token: 'keyword', foreground: '6366f1' }, // Electric Indigo
          { token: 'string', foreground: '06b6d4' },  // Cyber Cyan
          { token: 'function', foreground: '10b981' }, // Emerald Matrix
          { token: 'type', foreground: 'f59e0b' },     // Amber
        ],
        colors: {
          'editor.background': '#05050A', // Void Black
          'editor.foreground': '#f8fafc',
          'editorLineNumber.foreground': '#334155',
          'editor.lineHighlightBackground': '#ffffff05',
          'editor.selectionBackground': '#6366f140',
          'editorCursor.foreground': '#06b6d4', // Cyber Cyan pulsating cursor
        },
      });
      monaco.editor.setTheme('cyber-void');
    }
  }, [monaco]);

  return (
    <GlassCard className="w-full h-full flex flex-col p-0 overflow-hidden border-white/10 shadow-2xl bg-surface-glass/90">
      {/* Header bar of the code editor */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-white/10 bg-white/[0.02] backdrop-blur-md">
        <div className="flex items-center gap-3">
          {/* macOS-style glowing traffic light window controls */}
          <div className="flex gap-1.5">
            <div className="w-2.5 h-2.5 rounded-full bg-danger/80" />
            <div className="w-2.5 h-2.5 rounded-full bg-warning/80" />
            <div className="w-2.5 h-2.5 rounded-full bg-success/80" />
          </div>
          <div className="h-4 w-px bg-white/10" />
          <div className="flex items-center gap-1.5">
            <Terminal className="w-3.5 h-3.5 text-primary" />
            <span className="text-xs font-mono text-white/70 uppercase tracking-widest font-semibold">
              {language}
            </span>
          </div>
        </div>

        {/* Live SSE Stream Telemetry */}
        <div className="flex items-center gap-3">
          {isStreaming ? (
            <div className="flex items-center gap-2 px-2.5 py-1 rounded-full bg-primary/10 border border-primary/30 shadow-[0_0_12px_rgba(99,102,241,0.3)]">
              <span className="w-2 h-2 rounded-full bg-primary animate-pulse" />
              <span className="text-[10px] font-mono text-primary font-bold uppercase tracking-wider">
                {streamStatus || 'Generating Stream'}
              </span>
              {tokenCount > 0 && (
                <span className="text-[9px] font-mono text-white/40 border-l border-primary/20 pl-1.5">
                  {tokenCount} tokens
                </span>
              )}
            </div>
          ) : (
            <div className="flex items-center gap-1.5 text-[10px] font-mono text-white/40">
              <Sparkles className="w-3 h-3 text-success" />
              <span>Compilation Ready</span>
            </div>
          )}
        </div>
      </div>

      {/* Monaco Editor Canvas */}
      <div className="flex-grow relative">
        <Editor
          height="100%"
          language={language}
          value={code}
          theme="cyber-void"
          options={{
            readOnly: true, // The user monitors autonomous agent code generation
            minimap: { enabled: false },
            fontSize: 13,
            fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
            padding: { top: 16, bottom: 16 },
            scrollBeyondLastLine: false,
            smoothScrolling: true,
            cursorBlinking: isStreaming ? 'smooth' : 'solid',
            lineNumbers: 'on',
            renderLineHighlight: 'all',
          }}
          loading={
            <div className="flex items-center justify-center h-full text-white/30 gap-2 font-mono text-xs">
              <Loader2 className="w-5 h-5 animate-spin text-primary" />
              <span>Initializing Monaco Environment…</span>
            </div>
          }
        />

        {/* Real-time streaming bottom gradient glow */}
        {isStreaming && (
          <div className="absolute bottom-0 left-0 right-0 h-12 bg-gradient-to-t from-[#05050A] to-transparent pointer-events-none flex items-end justify-center pb-2">
            <span className="text-[9px] font-mono text-white/40 uppercase tracking-widest animate-pulse">
              ● Streaming Live Tokens from AI Developer Alex
            </span>
          </div>
        )}
      </div>
    </GlassCard>
  );
}
