'use client';

import React, { useState } from 'react';
import { toast } from 'sonner';
import {
  Download,
  Lock,
  Globe,
  GitBranch,
  CheckCircle2,
  Loader2,
  X,
  ExternalLink,
  Sparkles,
  ShieldCheck,
  FolderGit2,
} from 'lucide-react';
import { GlassCard, NeonButton } from '@/packages/ui';

interface GitHubExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId: string;
  projectName: string;
}

/**
 * Ultra-Modern Cyber Void GitHub Export & Repository Dispatcher.
 * Allows instant pushing of the AI-generated codebase directly to GitHub, or downloading a clean zip bundle.
 */
export function GitHubExportModal({
  isOpen,
  onClose,
  projectId,
  projectName,
}: GitHubExportModalProps) {
  const [repoName, setRepoName] = useState(
    projectName.toLowerCase().replace(/[^a-z0-9-_]/g, '-'),
  );
  const [isPrivate, setIsPrivate] = useState(true);
  const [branch, setBranch] = useState('main');
  const [commitMessage, setCommitMessage] = useState(
    `feat: Initial software architecture generated by AI Teams Platform`,
  );
  const [pushing, setPushing] = useState(false);
  const [exportSuccess, setExportSuccess] = useState<{ url: string } | null>(null);

  if (!isOpen) return null;

  const handlePushToGitHub = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!repoName.trim() || pushing) return;

    setPushing(true);
    setExportSuccess(null);

    try {
      const res = await fetch('/api/git/push', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          projectId,
          repoName: repoName.trim(),
          isPrivate,
          branch,
          commitMessage,
        }),
      });

      const json = await res.json().catch(() => null);

      if (!res.ok || !json?.success) {
        throw new Error(json?.error?.message || 'Failed to push repository to GitHub');
      }

      const repoUrl = json.data?.repoUrl || `https://github.com/${repoName}`;
      setExportSuccess({ url: repoUrl });
      toast.success('Repository Exported to GitHub', {
        description: `Successfully published to ${repoName}`,
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'GitHub export failed';
      toast.error('Export Failed', { description: message });
    } finally {
      setPushing(false);
    }
  };

  const handleDownloadZip = () => {
    toast.info('Preparing ZIP Package…', {
      description: 'Bundling project files for instant download.',
    });
    window.open(`/api/projects/${projectId}/export/zip`, '_blank');
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
      <div className="w-full max-w-lg animate-fade-up">
        <GlassCard className="p-8 border-primary/30 bg-[#070710]/95 shadow-[0_0_60px_rgba(99,102,241,0.25)] relative overflow-hidden">
          {/* Close button */}
          <button
            type="button"
            onClick={onClose}
            className="absolute top-5 right-5 text-white/40 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>

          {/* Modal Header */}
          <div className="flex items-center gap-3 mb-6">
            <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-white border border-white/20 shadow-md">
              <FolderGit2 className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold tracking-tight text-white">Export to GitHub</h2>
              <p className="text-xs text-white/50">
                Push your autonomous AI software build to a live repository.
              </p>
            </div>
          </div>

          {exportSuccess ? (
            /* Success View */
            <div className="space-y-6 text-center py-4">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-success/20 text-success border border-success/40 shadow-[0_0_20px_rgba(16,185,129,0.4)]">
                <CheckCircle2 className="w-7 h-7" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white">Repository Published!</h3>
                <p className="mt-1 text-xs text-white/60">
                  Your project code and documentation are now live on GitHub.
                </p>
              </div>
              <div className="flex flex-col sm:flex-row gap-3 pt-2">
                <a
                  href={exportSuccess.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex-1"
                >
                  <NeonButton variant="primary" className="w-full h-11 text-xs font-bold">
                    <span>Open on GitHub</span>
                    <ExternalLink className="w-3.5 h-3.5 ml-1.5" />
                  </NeonButton>
                </a>
                <button
                  type="button"
                  onClick={onClose}
                  className="h-11 px-5 rounded-xl border border-white/10 bg-white/5 text-white/70 hover:text-white text-xs font-bold transition-all"
                >
                  Done
                </button>
              </div>
            </div>
          ) : (
            /* Main Form View */
            <form onSubmit={handlePushToGitHub} className="space-y-5">
              {/* Repository Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold uppercase tracking-wider text-white/70">
                  Repository Name
                </label>
                <div className="relative">
                  <input
                    type="text"
                    required
                    value={repoName}
                    onChange={(e) => setRepoName(e.target.value)}
                    placeholder="my-ai-project"
                    className="w-full h-11 rounded-xl border border-white/10 bg-white/5 px-4 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-primary/60 focus:ring-2 focus:ring-primary/20 font-mono backdrop-blur-md"
                  />
                </div>
              </div>

              {/* Visibility & Branch Options */}
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold uppercase tracking-wider text-white/70">
                    Visibility
                  </label>
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={() => setIsPrivate(true)}
                      className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border text-xs font-bold transition-all ${
                        isPrivate
                          ? 'border-primary/80 bg-primary/20 text-white shadow-[0_0_12px_rgba(99,102,241,0.3)]'
                          : 'border-white/10 bg-white/5 text-white/50 hover:text-white'
                      }`}
                    >
                      <Lock className="w-3.5 h-3.5" />
                      Private
                    </button>
                    <button
                      type="button"
                      onClick={() => setIsPrivate(false)}
                      className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 rounded-xl border text-xs font-bold transition-all ${
                        !isPrivate
                          ? 'border-primary/80 bg-primary/20 text-white shadow-[0_0_12px_rgba(99,102,241,0.3)]'
                          : 'border-white/10 bg-white/5 text-white/50 hover:text-white'
                      }`}
                    >
                      <Globe className="w-3.5 h-3.5" />
                      Public
                    </button>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold uppercase tracking-wider text-white/70">
                    Target Branch
                  </label>
                  <div className="relative">
                    <input
                      type="text"
                      value={branch}
                      onChange={(e) => setBranch(e.target.value)}
                      placeholder="main"
                      className="w-full h-10 rounded-xl border border-white/10 bg-white/5 px-3.5 text-xs text-white font-mono placeholder:text-white/30 focus:outline-none focus:border-primary/60"
                    />
                  </div>
                </div>
              </div>

              {/* Commit Message */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold uppercase tracking-wider text-white/70">
                  Initial Commit Message
                </label>
                <input
                  type="text"
                  value={commitMessage}
                  onChange={(e) => setCommitMessage(e.target.value)}
                  className="w-full h-10 rounded-xl border border-white/10 bg-white/5 px-3.5 text-xs text-white placeholder:text-white/30 focus:outline-none focus:border-primary/60 font-mono"
                />
              </div>

              {/* Actions */}
              <div className="pt-3 space-y-3">
                <NeonButton
                  type="submit"
                  variant="primary"
                  isLoading={pushing}
                  disabled={pushing || !repoName.trim()}
                  className="w-full h-12 text-xs font-bold shadow-xl flex items-center justify-center gap-2"
                >
                  {pushing ? (
                    'Creating Repository & Pushing Code…'
                  ) : (
                    <>
                      <GitBranch className="w-4 h-4 mr-1" />
                      <span>Publish & Push to GitHub</span>
                    </>
                  )}
                </NeonButton>

                <div className="flex items-center justify-between text-xs pt-1 border-t border-white/5">
                  <span className="text-white/40 font-mono">Prefer a local archive?</span>
                  <button
                    type="button"
                    onClick={handleDownloadZip}
                    className="inline-flex items-center gap-1 font-semibold text-primary hover:underline"
                  >
                    <Download className="w-3.5 h-3.5" />
                    Download .zip bundle
                  </button>
                </div>
              </div>
            </form>
          )}
        </GlassCard>
      </div>
    </div>
  );
}
